"use strict"
const PIGEON_COUNT = 10;
const BIRD_SIZE = 10;

const BIRD_BRAIN_INPUT_LEN = 2;
const BIRD_BRAIN_HIDDEN_WIDTH = 1;
const BIRD_BRAIN_HIDDEN_HEIGHT = 4;
const BIRD_BRAIN_OUTPUT_LEN = 4;

const BIRD_SPEED = 2;

